spring:
  application:
    name: fincontrol-api

  datasource:
    url: jdbc:postgresql://localhost:5432/fincontrol
    username: fincontrol
    password: fincontrol123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  jwt:
    secret: f1nC0ntr0l-S3cr3t-K3y-Th4t-1s-L0ng-3n0ugh-F0r-HS256-Alg0r1thm-2026
    expiration-ms: 86400000 # 24 horas

logging:
  level:
    com.fincontrol: DEBUG
    org.springframework.security: DEBUG
