spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fincontrol_test
    username: fincontrol
    password: fincontrol123

  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false
